export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as GamerProfile} from './GamerProfile'
export {default as UsersList} from './UsersList'
export {default as SingleUser} from './SingleUser'
export {default as Profile} from './Profile'
export {default as Error} from './Error'